name: PR Validation

on:
  pull_request:
    branches:
      - main

jobs:
  validate-hedera-outputs:
    runs-on: ubuntu-latest
    steps:
      - name: 🚀 Checkout Repo
        uses: actions/checkout@v4

      - name: ⚙️ Setup Hedera Solo
        uses: ./
        id: solo

      - name: ✅ Validate Hedera Solo Outputs
        run: |
          # Validate ECDSA Outputs
          if [ -z "${{ steps.solo.outputs.ecdsaAccountId }}" ]; then
            echo "❌ Error: ECDSA accountId is missing!"
            exit 1
          fi
          if [ -z "${{ steps.solo.outputs.ecdsaPrivateKey }}" ]; then
            echo "❌ Error: ECDSA privateKey is missing!"
            exit 1
          fi
          if [ -z "${{ steps.solo.outputs.ecdsaPublicKey }}" ]; then
            echo "❌ Error: ECDSA publicKey is missing!"
            exit 1
          fi

          # Validate ED25519 Outputs
          if [ -z "${{ steps.solo.outputs.ed25519AccountId }}" ]; then
            echo "❌ Error: ED25519 accountId is missing!"
            exit 1
          fi
          if [ -z "${{ steps.solo.outputs.ed25519PrivateKey }}" ]; then
            echo "❌ Error: ED25519 privateKey is missing!"
            exit 1
          fi
          if [ -z "${{ steps.solo.outputs.ed25519PublicKey }}" ]; then
            echo "❌ Error: ED25519 publicKey is missing!"
            exit 1
          fi

          echo "🎉 All outputs are valid!"

  validate-mirror-node:
    runs-on: ubuntu-latest
    steps:
      - name: 🚀 Checkout Repo
        uses: actions/checkout@v4

      - name: ⚙️ Setup Hedera Solo with MirrorNode
        uses: ./
        with:
          installMirrorNode: true
        id: solo

      - name: ✅ Validate Mirror Node API
        run: |
          # Log Account details for both ECDSA and ED25519
          echo "ECDSA Account ID: ${{ steps.solo.outputs.ecdsaAccountId }}"
          echo "ECDSA Private Key: ${{ steps.solo.outputs.ecdsaPrivateKey }}"
          echo "ECDSA Public Key: ${{ steps.solo.outputs.ecdsaPublicKey }}"

          echo "ED25519 Account ID: ${{ steps.solo.outputs.ed25519AccountId }}"
          echo "ED25519 Private Key: ${{ steps.solo.outputs.ed25519PrivateKey }}"
          echo "ED25519 Public Key: ${{ steps.solo.outputs.ed25519PublicKey }}"

          # Wait for the mirror node to be fully up and running
          sleep 10

          RESPONSE=$(curl -s -w "%{http_code}" -X 'GET' 'http://localhost:8080/api/v1/network/nodes' -H 'accept: application/json' -o response.json)

          if [ "$RESPONSE" -ne 200 ]; then
            echo "❌ Error: API request failed with status code $RESPONSE"
            cat response.json
            exit 1
          else
            echo "✅ API request successful"
            cat response.json
          fi

  validate-json-rpc-relay:
    runs-on: ubuntu-latest
    steps:
      - name: 🚀 Checkout Repo
        uses: actions/checkout@v4

      - name: ⚙️ Setup Hedera Solo with JSON-RPC Relay
        uses: ./
        with:
          installRelay: true
        id: solo

      - name: ✅ Validate JSON-RPC Relay
        run: |
          # Log Account details for both ECDSA and ED25519
          echo "ECDSA Account ID: ${{ steps.solo.outputs.ecdsaAccountId }}"
          echo "ECDSA Public Key: ${{ steps.solo.outputs.ecdsaPublicKey }}"
          echo "ECDSA Private Key: ${{ steps.solo.outputs.ecdsaPrivateKey }}"

          echo "ED25519 Account ID: ${{ steps.solo.outputs.ed25519AccountId }}"
          echo "ED25519 Public Key: ${{ steps.solo.outputs.ed25519PublicKey }}"
          echo "ED25519 Private Key: ${{ steps.solo.outputs.ed25519PrivateKey }}"

          sleep 30
          RESPONSE=$(curl -s -w "%{http_code}" -X POST 'http://localhost:7546' \
            -H 'Content-Type: application/json' \
            -d '{"jsonrpc":"2.0","method":"eth_chainId","params":[],"id":1}' \
            -o response.json)
          if [ "$RESPONSE" -ne 200 ]; then
            echo "❌ Error: JSON-RPC request failed with status code $RESPONSE"
            echo "Response body:"
            cat response.json
            echo "Checking if relay service is running:"
            kubectl get pods -n solo | grep relay
            exit 1
          fi
          CHAIN_ID=$(jq -r '.result' response.json)
          if [ -z "$CHAIN_ID" ] || [ "$CHAIN_ID" = "null" ]; then
            echo "❌ Error: Invalid or missing chainId in response"
            echo "Response body:"
            cat response.json
            exit 1
          fi
          echo "✅ JSON-RPC Relay request successful"
          echo "Chain ID: $CHAIN_ID"
          cat response.json
